# Site settings

baseurl: ""
available: "en, de, fr, es, ru, it, ch, jp"

# SEO related

title: "Greentea OS"
author: "Greentea OS"
description: "Greentea OS is a free operating system"
image: "https://greenteaosforkbyrdpstudio.github.io/assets/images/opengraph.png"
url: "https://greenteaosforkbyrdpstudio.github.io"
theme-color: "#528a3f"

# Structure

collections:
  wiki:
    output: true
  blog:
    output: true

# Build settings

markdown: kramdown
highlighter: rouge
plugins:
   - jemoji
   - jekyll-seo-tag
   - jekyll-sitemap
kramdown:
  autolink: true
  input: GFM
  syntax_highlighter: rouge
